// <auto-generated />
using System;
using Med.Trading.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Med.Trading.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260720093029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Trading")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.InstrumentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DefaultProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 7, 20, 9, 30, 28, 771, DateTimeKind.Utc).AddTicks(3050));

                    b.Property<decimal>("Volume24h")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("VolumeLastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UpdatedOn", "IsActive")
                        .HasDatabaseName("IX_InstrumentEntity_IsActive");

                    b.HasIndex("VolumeLastUpdatedOn", "IsActive")
                        .HasDatabaseName("IX_InstrumentEntity_VolumeLastUpdatedOn_IsActive");

                    b.ToTable("Instruments", "Trading");
                });

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.TradeOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionMoney")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FilledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstrumentSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("PortfolioId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentSymbol");

                    b.HasIndex("PortfolioId");

                    b.ToTable("TradeOrders", "Trading");
                });

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.UserHoldingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvailableQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("InstrumentSymbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentSymbol");

                    b.HasIndex("UserId", "InstrumentSymbol")
                        .IsUnique()
                        .HasDatabaseName("UX_UserPortfolio_UserId_InstrumentSymbol")
                        .HasFilter("[InstrumentSymbol] IS NOT NULL");

                    b.ToTable("UserPortfolios", "Trading");
                });

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.TradeOrderEntity", b =>
                {
                    b.HasOne("Med.Trading.Core.Domain.Entities.InstrumentEntity", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentSymbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Med.Trading.Core.Domain.Entities.UserHoldingEntity", "Holding")
                        .WithMany("TradeOrders")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Holding");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.UserHoldingEntity", b =>
                {
                    b.HasOne("Med.Trading.Core.Domain.Entities.InstrumentEntity", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentSymbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Med.Trading.Core.Domain.Entities.UserHoldingEntity", b =>
                {
                    b.Navigation("TradeOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
